# Generated by Django 2.1.5 on 2019-01-24 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add',
            new_name='addp',
        ),
    ]
