# Generated by Django 2.1.5 on 2019-01-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190124_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addp',
            name='user',
        ),
        migrations.DeleteModel(
            name='addp',
        ),
    ]
